/* Downloads the openly-licensed books bundled with the study hub and
   rewrites library/library.json + library/ATTRIBUTION.md.

   Only material that may legally be redistributed is listed here:
   Creative Commons licences, US-government public domain, or Project
   Gutenberg public domain. Books that are free to read but NOT free to
   mirror (OSTEP, Handbook of Applied Cryptography, NCERT, SEBI/RBI
   circulars) stay as links in library.json -> links.

   Run: node tools/fetch-books.cjs           (skips files already present)
        node tools/fetch-books.cjs --force   (re-downloads everything)
*/
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const root = path.resolve(__dirname, '..');
const force = process.argv.includes('--force');
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)';

/* Original project material — not downloaded, generated by other tools. */
const originals = [
  { id: 'study-handbook', file: 'library/study-handbook.pdf', title: 'Your 180-day study handbook',
    desc: 'Complete daily plan, weekly targets and study routines. Printable PDF.',
    subject: 'Plan', license: 'Original study guide' },
  { id: 'study-handbook-word', file: 'library/study-handbook.docx', title: 'Your 180-day handbook · Word',
    desc: 'Editable DOCX version. Read here or download for personal planning.',
    subject: 'Plan', license: 'Original study guide' },
  { id: 'complete-notes', file: 'library/complete-study-notes.pdf', title: 'Complete study notes · offline collection',
    desc: 'All 142 topic notes in one reference. The fastest way to revise away from the app.',
    subject: 'All subjects', license: 'Original study notes' }
];

/* Third-party books, all redistributable. */
const books = [
  {
    id: 'open-data-structures', file: 'library/open-data-structures.pdf',
    title: 'Open Data Structures · Java',
    author: 'Pat Morin', subject: 'Data Structures',
    desc: 'Full textbook: arrays, lists, hashing, trees, heaps and graphs. Begin with chapters 1-3, 5-6 and 10.',
    source: 'https://opendatastructures.org/',
    url: 'https://opendatastructures.org/ods-java.pdf',
    license: 'CC BY · unmodified original'
  },
  {
    id: 'think-python', file: 'library/think-python.pdf',
    title: 'Think Python · Second edition',
    author: 'Allen B. Downey', subject: 'Programming',
    desc: 'Python foundations, functions, collections and objects. A full introductory book for daily reading.',
    source: 'https://greenteapress.com/wp/think-python-2e/',
    url: 'https://greenteapress.com/thinkpython2/thinkpython2.pdf',
    license: 'CC BY-NC 3.0 · unmodified · noncommercial study use'
  },
  {
    id: 'algorithms', file: 'library/algorithms.pdf',
    title: 'Algorithms',
    author: 'Jeff Erickson', subject: 'Algorithms',
    desc: 'Deep practice in recursion, backtracking, greedy algorithms and dynamic programming.',
    source: 'https://jeffe.cs.illinois.edu/teaching/algorithms/',
    url: 'https://jeffe.cs.illinois.edu/teaching/algorithms/book/Algorithms-JeffE.pdf',
    license: 'CC BY 4.0 · unmodified original'
  },
  {
    id: 'cn-systems-approach', file: 'library/computer-networks-systems-approach.pdf',
    title: 'Computer Networks: A Systems Approach',
    author: 'Larry Peterson & Bruce Davie', subject: 'Computer Networks',
    desc: 'Full university textbook. Read chapters 1-2 (foundation, links), 3 (switching), 4 (internetworking), 5 (transport) and 8 (security).',
    source: 'https://book.systemsapproach.org/',
    url: 'https://github.com/SystemsApproach/book/releases/download/v6.1/book.pdf',
    license: 'CC BY 4.0 · unmodified release v6.1'
  },
  {
    id: 'database-design', file: 'library/database-design.pdf',
    title: 'Database Design · Second edition',
    author: 'Adrienne Watt & Nelson Eng', subject: 'DBMS',
    desc: 'Open textbook covering the relational model, ER modelling, normalisation and SQL basics.',
    source: 'https://opentextbc.ca/dbdesign01/',
    url: 'https://opentextbc.ca/dbdesign01/open/download?type=pdf',
    license: 'CC BY 4.0 · BCcampus Open Education · unmodified'
  },
  {
    id: 'little-book-semaphores', file: 'library/little-book-of-semaphores.pdf',
    title: 'The Little Book of Semaphores',
    author: 'Allen B. Downey', subject: 'Operating Systems',
    desc: 'Process synchronisation in depth — producer-consumer, readers-writers, dining philosophers, and every classic problem with worked solutions.',
    source: 'https://greenteapress.com/wp/semaphores/',
    url: 'https://greenteapress.com/semaphores/LittleBookOfSemaphores.pdf',
    license: 'CC BY-NC · unmodified · noncommercial study use'
  },
  {
    id: 'crypto101', file: 'library/crypto-101.pdf',
    title: 'Crypto 101',
    author: 'Laurens Van Houtven', subject: 'Cyber Security',
    desc: 'Introductory cryptography: block ciphers, modes, hashes, MACs, signatures and how they fail. Pairs with the cryptography notes.',
    source: 'https://www.crypto101.io/',
    url: 'https://crypto101.io/Crypto101.pdf',
    license: 'CC BY-NC 4.0 · unmodified'
  },
  {
    id: 'nist-800-207', file: 'library/nist-sp-800-207-zero-trust.pdf',
    title: 'NIST SP 800-207 · Zero Trust Architecture',
    author: 'NIST', subject: 'Cyber Security',
    desc: 'The definitive zero-trust reference. Read the tenets in section 2 — quotable in the descriptive paper and the interview.',
    source: 'https://csrc.nist.gov/pubs/sp/800/207/final',
    url: 'https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-207.pdf',
    license: 'US Government work · public domain'
  },
  {
    id: 'nist-800-61r3', file: 'library/nist-sp-800-61r3-incident-response.pdf',
    title: 'NIST SP 800-61r3 · Incident Response',
    author: 'NIST', subject: 'Cyber Security',
    desc: 'Incident handling lifecycle. Maps directly onto SEBI CSCRF respond-and-recover expectations.',
    source: 'https://csrc.nist.gov/pubs/sp/800/61/r3/final',
    url: 'https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-61r3.pdf',
    license: 'US Government work · public domain'
  },
  {
    id: 'nist-800-145', file: 'library/nist-sp-800-145-cloud.pdf',
    title: 'NIST SP 800-145 · The NIST Definition of Cloud Computing',
    author: 'NIST', subject: 'Cloud',
    desc: 'Three pages. The five essential characteristics and the service/deployment models every cloud question is built on.',
    source: 'https://csrc.nist.gov/pubs/sp/800/145/final',
    url: 'https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-145.pdf',
    license: 'US Government work · public domain'
  },
  {
    id: 'elements-of-style', file: 'library/elements-of-style.txt',
    title: 'The Elements of Style',
    author: 'William Strunk Jr.', subject: 'English (Descriptive)',
    desc: 'Short, public-domain style guide. One read improves the Phase II descriptive paper more than any grammar drill.',
    source: 'https://www.gutenberg.org/ebooks/37134',
    url: 'https://www.gutenberg.org/cache/epub/37134/pg37134.txt',
    license: 'Public domain · Project Gutenberg'
  }
];

function fetchFile(url) {
  return execFileSync('curl.exe',
    ['-f', '-sS', '-L', '-A', UA, '--connect-timeout', '20', '--max-time', '600', url],
    { maxBuffer: 120 * 1024 * 1024, timeout: 620000 });
}

(async () => {
  let downloaded = 0;
  for (const b of books) {
    const dest = path.join(root, b.file);
    if (force || !fs.existsSync(dest)) {
      process.stdout.write(`downloading ${b.title} … `);
      const bytes = fetchFile(b.url);
      const isPdf = b.file.endsWith('.pdf');
      if (isPdf && bytes.subarray(0, 5).toString() !== '%PDF-') throw new Error('Not a PDF: ' + b.title);
      if (!isPdf && bytes.length < 1000) throw new Error('Suspiciously small: ' + b.title);
      fs.writeFileSync(dest, bytes);
      downloaded++;
      console.log('ok');
    }
    console.log(`  ${b.title}: ${Math.round(fs.statSync(dest).size / 1024)} KB`);
  }

  /* rewrite library.json books list, keeping the links section intact */
  const shelfPath = path.join(root, 'library/library.json');
  const shelf = JSON.parse(fs.readFileSync(shelfPath, 'utf8'));
  shelf.books = [...originals, ...books.map(({ url, ...rest }) => rest)];
  fs.writeFileSync(shelfPath, JSON.stringify(shelf, null, 2) + '\n');

  /* rewrite attribution */
  const lines = books.map(b =>
    `- **${b.title}**, ${b.author}. Unmodified file from ${b.url}. Source: ${b.source}. Licence: ${b.license}.`);
  fs.writeFileSync(path.join(root, 'library/ATTRIBUTION.md'),
`# Included book attribution

Every third-party file bundled with this site is redistributable under the
licence shown. Files are unmodified originals.

${lines.join('\n')}

The 180-day handbook and the compiled study-note collection are original
project material.

## Deliberately not bundled

Some excellent free books may be read online but not mirrored, so this site
links to them instead of copying them:

- **Operating Systems: Three Easy Pieces** (Arpaci-Dusseau) — free chapters are published on the authors' own site, while the combined PDF is sold. Download from https://pages.cs.wisc.edu/~remzi/OSTEP/
- **Handbook of Applied Cryptography** (Menezes et al.) — free to download for personal use; copyright CRC Press. https://cacr.uwaterloo.ca/hac/
- **SEBI, RBI, CERT-In and MeitY publications** — these are the live regulatory position and must be read current. A cached copy of a superseded circular is worse than none.
- **NCERT textbooks** — free to download from https://ncert.nic.in but copyright NCERT.

This site is an independent preparation aid. It is not affiliated with SEBI,
NIST, or any textbook author, and no endorsement should be inferred. The
licence of each third-party work remains in force.
`);

  const total = shelf.books.reduce((a, b) => a + fs.statSync(path.join(root, b.file)).size, 0);
  console.log(`\n${shelf.books.length} books in library.json (${downloaded} newly downloaded), ${Math.round(total / 1048576)} MB total.`);
})().catch(e => { console.error(e.message); process.exitCode = 1; });
