const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..');
function edit(file,fn){const p=path.join(root,file);fs.writeFileSync(p,fn(fs.readFileSync(p,'utf8').replace(/\r\n/g,'\n')));}
edit('tools/complete-content.cjs',s=>s.replaceAll(String.fromCharCode(96).repeat(3),String.fromCharCode(92,96).repeat(3)));
edit('index.html',s=>s.replace('assets/icons/icon-192.png','assets/icons/icon.svg').replace('<script type="module" src="assets/js/app.js"></script>','<script src="assets/vendor/purify.min.js"></script>\n<script type="module" src="assets/js/app.js"></script>'));
edit('assets/js/util.js',s=>s.split('\n').map(line=>line.includes("return out.join('\\n')")?line.replace('return out.join', 'return window.DOMPurify.sanitize(out.join').replace(/;$/, ', { USE_PROFILES: { html: true } });'):line).join('\n').replace("i.onchange = () => { res(i.files[0] || null); i.remove(); };","i.onchange = () => { res(i.files[0] || null); i.remove(); };\n    i.oncancel = () => { res(null); i.remove(); };"));
edit('assets/js/views/notes.js',s=>s.replace(/  ta.oninput = .*;/,'  ta.oninput = () => { S.setUserNote(id, ta.value); status.textContent = "Saved on this device"; };'));
edit('assets/js/views/syllabus.js',s=>s.replace("  const wrap = el('div', {});",`  const wrap = el('div', {});
  if (syl.source) wrap.append(el('p', { class:'small' }, el('a', { href:syl.source.url,target:'_blank',rel:'noopener' }, 'Official 2025 notice · checked '+syl.source.checked), ' · ', el('a', {href:'https://www.sebi.gov.in/sebiweb/about/AboutAction.do?doVacancies=yes',target:'_blank',rel:'noopener'}, 'Recruitment updates')));
  for (const [phase,rows] of Object.entries(syl.weights || {})) wrap.append(el('div',{class:'card',style:'margin-bottom:16px'},el('h2',{},phase==='phase1'?'Phase I IT · indicative weights':'Phase II IT · indicative weights'),el('table',{class:'tbl'},el('tbody',{},...rows.map(([label,weight])=>el('tr',{},el('td',{},label),el('td',{},weight+'%')))))));
`).replace('Everyone attempting the IT stream is a CS/IT graduate — depth plus market context is what separates ranks.','Trace code, debug logic and work data examples. Use the official topic weights to allocate effort.').replace('It pays in Paper 1, in the IT descriptive answers, and again in the interview. Do it daily, never in a burst.','Use dated official sources for the common paper and interview examples.').replace('Start writing by hand/keyboard from Phase B of the plan, one answer a day.','Start typing and reviewing English drafts from the first week.'));
edit('assets/js/views/roadmap.js',s=>s.replace("t.n ? el('a',", "t.url ? el('a', { href:t.url, class:'link-btn', onclick:e=>e.stopPropagation() }, 'start activity →') : '',\n          t.n ? el('a',").replace('            fill(w, body);','            fill(w, body);\n            root.dispatchEvent(new CustomEvent("task:toggle"));').replace("  const weekEls = new Map();",`  root.addEventListener('task:toggle',()=>{
    for (const w of plan.weeks) {
      const wk=document.getElementById('wk'+w.n); if(!wk)continue;
      const total=w.days.reduce((a,d)=>a+d.tasks.length,0), done=w.days.reduce((a,d)=>a+S.dayDone(d.n,d.tasks.length),0);
      wk.querySelector('.wk-prog .bar i').style.width=pct(done,total)+'%';
      wk.querySelector('.wk-prog .xsmall').textContent=done+'/'+total;
    }
  });
  const weekEls = new Map();`));
edit('assets/js/views/dashboard.js',s=>s.replace('todayCard.append(taskList(day));','todayCard.append(taskList(day, subjMap));').replace('  root.append(tiles);',`  root.append(tiles);
  if(!S.settings.name) root.append(el('div',{class:'card welcome-card',style:'margin-bottom:18px'},el('div',{class:'eyebrow'},'YOUR NEXT CHAPTER'),el('h2',{},'A little progress, every day.'),el('p',{class:'small muted'},'Start with today’s linked lessons. This plan uses four focused hours a day and the official 2025 IT syllabus as its baseline.'),el('div',{class:'btn-row'},el('a',{class:'btn primary',href:'#/settings'},'Personalise your plan'),el('a',{class:'btn',href:'#/library'},'Explore the included books'))));
  root.addEventListener('task:toggle',async()=>{
    const fresh=await planProgress(), paceNow=await pacing();
    tiles.children[0].querySelector('.v').textContent=S.dayDone(day.n,day.tasks.length)+'/'+day.tasks.length;
    tiles.children[2].querySelector('.v').textContent=fresh.pct+'%';
    tiles.children[2].querySelector('.d').textContent=fresh.done+' of '+fresh.total+' tasks';
    tiles.children[3].querySelector('.v').textContent=paceNow.pct+'%';
  });`).replace("  applyMQ(); mq.addEventListener('change', applyMQ);",`  applyMQ(); mq.addEventListener('change', applyMQ);
  const observer=new MutationObserver(()=>{if(!root.isConnected){mq.removeEventListener('change',applyMQ);observer.disconnect();}});observer.observe(document.body,{childList:true,subtree:true});`));
edit('assets/js/app.js',s=>s.replace("import { $, $$, toast, hm, el }", "import { $, $$, toast, hm, el, esc }").replace('    await fn(view, { params, query, name });',"    const pageRoot=el('div'); view.append(pageRoot);\n    await fn(pageRoot, { params, query, name });").replace('${e.message}','${esc(e.message)}').replace("  $('#streakChip').textContent", "  cd.onclick = () => location.hash = '#/settings'; cd.style.cursor='pointer';\n  $('#streakChip').textContent").replace("  window.addEventListener('state:change', paintChrome);", "  window.addEventListener('state:change', paintChrome);\n  window.addEventListener('storage:failed',()=>toast('Your browser could not save progress. Export a backup before closing.',7000));\n  if ('serviceWorker' in navigator) navigator.serviceWorker.ready.then(()=>{S.m('offlineReady',true);});"));
edit('assets/js/views/settings.js',s=>s.replace('          S.set(\'settings.name\', name.value.trim());',`          if(!start.value || !hours.checkValidity() || !Number.isFinite(+hours.value)) { toast('Enter a valid start date and 1–16 daily hours'); return; }
          S.set('settings.name', name.value.trim());`).replace("          if (!m) { toast('Enter minutes'); return; }","          if (!Number.isFinite(m) || m <= 0 || m > 1440) { toast('Enter 1–1440 minutes'); return; }").replace('    el(\'h2\', {}, \'Backup & sync between devices\'),',`    el('h2', {}, 'Backup & transfer between devices'),
    el('p', {class:'small muted'}, 'Import replaces this device’s progress. Export first. Backups include progress and notes, but not locally opened PDF/DOCX files; transfer those separately.'),`).replace('            S.import(await f.text());',"            if (!confirmBox('Replace this device’s progress with this backup? Export first if you want to keep it.')) return;\n            S.import(await f.text());").replace('It then opens full-screen like an app, and the notes, roadmap and question bank work without internet.','Keep the page open while the initial offline download finishes. The status below confirms readiness.').replace("    el('h2', {}, 'Use it offline / install on your phone'),",`    el('h2', {}, 'Use it offline / install on your phone'),
    el('p', {class:'small'}, S.m('offlineReady')?'Offline app installed in this browser. Open each PDF once online to cache it too.':'Initial offline download is pending. Stay connected, then revisit this screen.'),`));
edit('assets/js/views/practice.js',s=>s.replace('questions across the full syllabus. Practice mode explains every answer; test mode times you like the real paper.','original questions across core areas. Explanations support learning; this is not an official paper or full mock series.').replace("  const timerLbl = el('span'", "  let finished=false;\n  const budget=questions.length*60;\n  const timerLbl = el('span'").replace('      const budget = questions.length * 36; // ~36s per question','      if(s>=budget){finish();return;}').replace('  function finish() {','  function finish() {\n    if(finished)return;finished=true;clearInterval(tick);').replace('    card.append(opts_);',`    if(!isTest && answers[i]!==null){
      [...opts_.children].forEach((row,k)=>{row.classList.add('disabled');if(k===q.a)row.classList.add('right');else if(k===answers[i])row.classList.add('wrong');});
      card.append(el('div',{class:'expl'},q.e));
    }
    card.append(opts_);`).replace('    const attempted = answers.filter(a => a !== null).length;', '    const attempted = answers.filter(a => a !== null).length;\n    const net=correct-(attempted-correct)*0.25;').replace('      stat(\'Score\', `${correct}/${questions.length}`, p + \'%\',', '      stat(\'Net score\', `${net}/${questions.length}`, `${correct} correct · −0.25 per wrong`,').replace("  const stat = (k, v, d, c)","  const cleanup=new MutationObserver(()=>{if(!head.isConnected){clearInterval(tick);cleanup.disconnect();}});cleanup.observe(document.body,{childList:true,subtree:true});\n  const stat = (k, v, d, c)").replace("opts.title || (isTest ? 'Timed test' : 'Practice set')", "opts.title || (isTest ? 'Timed drill · 60 seconds per question' : 'Practice set')"));
edit('assets/js/views/flashcards.js',s=>s.replace("    if (e.key === '1')", "    if (actions.style.visibility === 'hidden') return;\n    if (e.key === '1')"));
edit('data/notes/it-prog-output.md',s=>s.replace('marks you can guarantee with practice','skills you can improve with practice').replace('sizeof(p)  // 8  (pointer size)','sizeof(p)  // implementation-dependent pointer size; often 8 on 64-bit').replace('// 10 - but 1 if computed inside a function','// 10 here; invalid element-count formula for a pointer parameter'));
edit('assets/js/app.js',s=>s.replace('import { $, $, toast, hm, el, esc }',()=> 'import { $, $$, toast, hm, el, esc }'));
console.log('Applied app completion fixes. Run once only.');
